### ISSUE TITLE
Asset generation fails

### ISSUE THREAD

**Issue by RalfJung** [opatut/dudel#118]
Steps to reproduce:

* Get a fresh clone.
* Follow the steps in the README to get it started. (Also install WTForms, see my recent pull request #117 .)
* Do `make seed && make run`
* Access the test webserver

The asset generation of some SCSS file fails:
```
Traceback (most recent call last):
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/r/src/dudel/dudel/views.py", line 105, in index
    user_count=user_count)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/r/src/dudel/dudel/templates/index.jade", line 1, in top-level template code
    extends BASE.jade
  File "/home/r/src/dudel/dudel/templates/BASE.jade", line 7, in top-level template code
    meta(name="viewport", content="width=device-width, initial-scale=1.0")
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/bundle.py", line 746, in _urls
    *args, **kwargs)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/bundle.py", line 600, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/bundle.py", line 485, in _merge_and_apply
    filters_to_pass_down, disable_cache=disable_cache)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/bundle.py", line 524, in _merge_and_apply
    kwargs=item_data)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/merge.py", line 277, in apply
    return self._wrap_cache(key, func)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/merge.py", line 219, in _wrap_cache
    content = func().getvalue()
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/merge.py", line 252, in func
    getattr(filter, type)(data, out, **kwargs_final)
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/filter/sass.py", line 146, in input
    self._apply_sass(_in, out, os.path.dirname(source_path))
  File "/home/r/src/dudel/dudel-env/lib/python2.7/site-packages/webassets/filter/sass.py", line 133, in _apply_sass
    stderr, stdout, proc.returncode))
FilterError: sass: subprocess had error: stderr=Error: File to import not found or unreadable: vars.
```

Closer inspection with the interactive in-browser debugger shows that this is `main.scss`. It imports `vars`, which does not seem to be a file that exists. Replacing this by `_vars.css` makes the error change (it complains about a non-existing variable `$silver`). Is there something wrong with my installation, or are the SCSS files just broken?

**Comment by RalfJung** [comment]
I can reproduce the same error when compiling on the command-line with `scss --stdin < main.scss`. I can fix the error with `scss --stdin < main.scss  -I`.

The [SASS changelog](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html) indicates that importing relative to the working directory is deprecated.

**Comment by phi1010** [comment]
Requires

    filters=get_filter('scss', load_paths=['./scss']),

to work for me when using `python2 managepy runserver`, otherwise the load path ends at `.../dudel/static`, and causes an equal error message as above.
