### ISSUE TITLE
Update Documentation for Setup

### ISSUE THREAD

**Issue by HeinzLetscho** [opatut/dudel#74]
### Original Title: OSError: [Errno 2] No such file or directory

I set up dudel (Version 2.0.0) with an sqlite test db like it is described in the readme. All modules from requirements.txt were successfully installed. When I try to access the development server in the browser I get an  OSError: [Errno 2] No such file or directory.

Version 1.1.0 works well on the same server.

The entire traceback looks like this:

Traceback (most recent call last):
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/raven/middleware.py", line 35, in __call__
    iterable = self.application(environ, start_response)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/dudel20/dudel-2.0.0/dudel/views.py", line 116, in index
    return render_template("index.html", polls=polls, form=form, poll_count=poll_count, vote_count=vote_count, user_count=user_count)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/dudel20/dudel-2.0.0/dudel/templates/index.html", line 1, in top-level template code
    {% extends "BASE.html" %}
  File "/var/www/dudel20/dudel-2.0.0/dudel/templates/BASE.html", line 9, in top-level template code
    {% assets "css_all" -%}
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/ext/jinja2.py", line 186, in _render_assets
    urls = bundle.urls()
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/bundle.py", line 746, in _urls
    *args, **kwargs)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/bundle.py", line 600, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/bundle.py", line 485, in _merge_and_apply
    filters_to_pass_down, disable_cache=disable_cache)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/bundle.py", line 524, in _merge_and_apply
    kwargs=item_data)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/merge.py", line 277, in apply
    return self._wrap_cache(key, func)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/merge.py", line 219, in _wrap_cache
    content = func().getvalue()
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/merge.py", line 252, in func
    getattr(filter, type)(data, out, **kwargs_final)
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/filter/sass.py", line 146, in input
    self._apply_sass(_in, out, os.path.dirname(source_path))
  File "/var/www/dudel20/virenv/lib/python2.7/site-packages/webassets/filter/sass.py", line 127, in _apply_sass
    shell=(os.name == 'nt'))
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Akasch** [comment]
What OS do you use? The trace looks like Windows i think

**Comment by HeinzLetscho** [comment]
Its a Debian 7 server, x86_64.

**Comment by opatut** [comment]
You need to install sass on your system. There is a ruby gem, in case your package manager does not provide a sass package. 

Sorry for not stating this dependency in the readme. I admit there is some room for improvement in the documentation. 

Do not hesitate to contact me directly in the meantime, should you have issues setting up Dudel.

**Comment by opatut** [comment]
PS I had to change my account email because my mail server is down ;) Just in case you already sent one, please resend.

**Comment by HeinzLetscho** [comment]
Thank you for the quick support :) Now after I installed sass (with gem) and additionally coffeescript the development server can be accessed :)
