### ISSUE TITLE
Error with new PollType

### ISSUE THREAD

**Issue by Akasch** [opatut/dudel#89]
if i try to run dudel on master i get the following:

     ./manage.py runserver
    Raven is not configured (logging is disabled). Please see the documentation for more information.
    Traceback (most recent call last):
      File "./manage.py", line 2, in <module>
        from dudel import manager
      File "/home/nils/git/vm/dudel/dudel/__init__.py", line 35, in <module>
        import dudel.forms
      File "/home/nils/git/vm/dudel/dudel/forms.py", line 118, in <module>
         class CreatePollForm(PollForm):
       File "/home/nils/git/vm/dudel/dudel/forms.py", line 120, in CreatePollForm
        choices=[(choice.value, choice.title) for choice in PollType])
    TypeError: 'type' object is not iterable

**Comment by Akasch** [comment]
found the solution:

I have to install the pip package enum34.
